apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80        # This is the port that the service exposes
      targetPort: 3000 # This is the port on which the container is listening
  type: NodePort